### CREATE book
POST http://localhost:4004/odata/v4/admin/Books
Content-Type: application/json
Authorization: Basic alice:123

{
  "ID": 2,
  "title": "Poems : Pocket Poets",
  "descr": "The Everyman's Library Pocket Poets hardcover series is popular for its compact size and reasonable price which does not compromise content. Poems: Bronte contains poems that demonstrate a sensibility elemental in its force with an imaginative discipline and flexibility of the highest order. Also included are an Editor's Note and an index of first lines.",
  "author": { "ID": 101 },
  "stock": 5,
  "price": "12.05",
  "currency": { "code": "USD" }
}

### READ book
GET http://localhost:4004/odata/v4/admin/Books(ID=2)
Authorization: Basic alice:123

### UPDATE book
PATCH http://localhost:4004/odata/v4/admin/Books(ID=2)
Content-Type: application/json
Authorization: Basic alice:123

{
  "price": "15.00"
}

### DELETE book
DELETE http://localhost:4004/odata/v4/admin/Books(ID=2)
Authorization: Basic alice:123

### READ book unauthorized
GET http://localhost:4004/odata/v4/admin/Books(ID=2)
Authorization: Basic bob:123
